### ISSUE TITLE
Does it work when the device has multiple fingerprint enrolled from different user?

### ISSUE THREAD

**Issue by renznamoc21** [mjwheatley/ionic2-meteor-login#1]
Does it work when the device has multiple fingerprint enrolled from different user?

**Comment by mjwheatley** [comment]
Any fingerprint enrolled on a device can be used for authentication for any account that has enabled fingerprint auth for that device.

**Comment by renznamoc21** [comment]
Thanks. another question . does it possible to to use fingerprint auth
using the register fingerprint in the application? event there are two
different user register in device?

**Comment by mjwheatley** [comment]
I don't really understand your question.  The plugin does not differentiate between fingerprints.  Any registered fingerprint can be used for authentication.  No matter which fingerprint was used to do the encryption, any fingerprint registered on the device can authorize decryption of the token.

**Comment by renznamoc21** [comment]
do you think sir it is posible to retriieve unique key in keystore or
device fingerprint manager base on registered fingerprint using the plugin?

**Comment by mjwheatley** [comment]
What are you trying to accomplish?

**Comment by renznamoc21** [comment]
to authenticate fingerprint that only register using fingerprint auth
plugin even there is multiple user enrolled in device

**Comment by mjwheatley** [comment]
This is not possible.  The Android API does not allow for this.  
The API does not return any information regarding which fingerprint enrolled on the device matched the probe.  Therefore, during encryption, there is not way to know which fingerprint was used.
Furthermore there is no way to specify which enrolled fingerprint to match against.

**Comment by renznamoc21** [comment]
thank you very much sir

**Comment by mjwheatley** [comment]
How are you wanting to use fingerprint authentication?  Are you wanting to use it for login purposes like in this repo?

**Comment by renznamoc21** [comment]
yes i want it to use as login authentication

**Comment by mjwheatley** [comment]
Are you wanting to use it as a convenience for not having to type a password, or are you actually wanting secure login?

**Comment by mjwheatley** [comment]
I have also developed a password-less multi-factor OAuth2 system.  Check out [PassPrint](https://www.passprint.me) and let me know if you are interested in being a Beta tester.
However, it would require your users to register on the platform and use the authenticator app to login to your application.  You would register your app as an OAuth client with the platform, just like you would for Google or Facebook.
